<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트 타입 - 여러개의 자식 태그 + 수량
<!ELEMENT 타입 (자식태그명, 자식태그명, ...)>
 -->

<!-- book 자식태그로 book이 온다면 무슨 타입인지 알려줘야한다-->
<!DOCTYPE books[
<!ELEMENT books (book)*> 
<!ELEMENT book (title,author+,press,page,description?,photo*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>	
]>
<!-- 나열된 순서를 지켜야 한다 -->
<books>
<book>
<title>asd</title>
<author>ddd</author>
<press>ccc</press>
<page>asd</page>
<description>d</description>
</book>
<book>
<title>asd</title>
<author>ddd</author>
<press>ccc</press>
<page>asd</page>
</book>
</books>




