<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트 타입 - EMPTY <!ELEMENT 이름 EMPTY> -->

<!-- book 자식태그로 book이 온다면 무슨 타입인지 알려줘야한다 -->
<!DOCTYPE books[
<!ELEMENT books (book)*> 
<!ELEMENT book (title,author+,press,page,description?,photo*,cd?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT cd EMPTY>	
]>
<!-- 나열된 순서를 지켜야 한다 -->
<books>
	<book>
		<title>asd</title>
		<author>ddd</author>
		<press>ccc</press>
		<page>asd</page>
		<description>d</description>
		<cd></cd>
	</book>
	<book>
		<title>asd</title>
		<author>ddd</author>
		<press>ccc</press>
		<page>asd</page>
		<cd/>
	</book>
</books>




